import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import MenuItem from '../components/MenuItem'
import Link from 'next/link'
import NavBar from '../components/NavBar'
import Hero from '../components/Hero'
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Super App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <NavBar/>
      
      <Hero/>
      
    </div>
  )
}

export default Home
